### ISSUE TITLE
OpenEncryptedWithPass() cannot take ModeFlags.WriteRead

### ISSUE THREAD

**Issue by MrRobinOfficial** [Ardot66/SaveAccess#1]
I found a bug, that revolves around encrypting a file and calling `OpenEncryptedWithPass()` function (`SaveAccess.cs:90`):

```csharp
FileAccess.OpenEncryptedWithPass(filePath, FileAccess.ModeFlags.WriteRead, pass);
```

Changing from `FileAccess.ModeFlags.WriteRead` to `FileAccess.ModeFlags.Write` will allow the file to be written and saved correctly.

EDIT:

The same goes for `OpenEncrypted()` function.

**Comment by Ardot66** [comment]
Thanks for finding this! Turns out that [WriteRead isn't supported](https://github.com/godotengine/godot/issues/32881) by OpenEncrypedWithPass. I'll commit the fix and get the next version uploaded. Not completely sure why I was using WriteRead anyway, as I was only writing with it.
